# Generated by Django 5.0.7 on 2024-08-02 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunil', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
