# Generated by Django 5.0.7 on 2024-09-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sunil', '0002_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generate_date', models.DateField(auto_now_add=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('total_in', models.IntegerField()),
                ('total_out', models.IntegerField()),
                ('hosting', models.FloatField()),
                ('total', models.FloatField()),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
