# Generated by Django 5.0.7 on 2024-09-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunil', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='paid_date',
            field=models.DateField(null=True),
        ),
    ]
