# Generated by Django 5.0.7 on 2024-08-03 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('office', '0007_rename_product_item_rename_product_batch_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='In_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.IntegerField(null=True, unique=True)),
                ('status', models.CharField(choices=[('1', 'Production'), ('2', 'Return')], max_length=50)),
                ('generate_date', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='office.employee')),
                ('item', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='office.item')),
                ('qr_code', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='office.qr_code')),
            ],
        ),
    ]
