# Generated by Django 5.0.7 on 2024-08-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_stock',
            name='scan_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='in_stock',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
