# Generated by Django 5.0.7 on 2024-08-03 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_rename_product_item_rename_product_batch_item_and_more'),
        ('store', '0003_rename_in_stock_in_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('verify_by', models.CharField(max_length=100, null=True)),
                ('verify_status', models.IntegerField(max_length=100, null=True)),
                ('verify_date', models.DateTimeField(null=True)),
                ('employee', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='office.employee')),
            ],
        ),
    ]
