# Generated by Django 5.0.7 on 2024-08-05 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_rename_product_item_rename_product_batch_item_and_more'),
        ('store', '0004_voucher_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Out_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.IntegerField(null=True, unique=True)),
                ('generate_date', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('verify_status', models.IntegerField(default=0, null=True)),
                ('verify_date', models.DateTimeField(null=True)),
                ('verify_by', models.CharField(max_length=100, null=True)),
                ('scan_type', models.CharField(max_length=100, null=True)),
                ('employee', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='office.employee')),
                ('item', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='office.item')),
                ('qr_code', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='office.qr_code')),
                ('voucher', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='store.voucher_name')),
            ],
        ),
    ]
