# Generated by Django 5.0.7 on 2024-08-05 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_rename_product_item_rename_product_batch_item_and_more'),
        ('store', '0005_out_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Out_stock',
            new_name='Out_item',
        ),
    ]
