# Generated by Django 5.0.7 on 2024-08-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_out_stock_out_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher_name',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
