# Generated by Django 5.0.7 on 2024-08-11 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0012_remove_employee_department_and_more'),
        ('store', '0007_voucher_name_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='in_item',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='out_item',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='voucher_name',
            name='employee',
        ),
        migrations.AddField(
            model_name='in_item',
            name='in_employee',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='office.in_employee'),
        ),
        migrations.AddField(
            model_name='out_item',
            name='out_employee',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='office.out_employee'),
        ),
        migrations.AddField(
            model_name='voucher_name',
            name='out_employee',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='office.out_employee'),
        ),
        migrations.AlterField(
            model_name='out_item',
            name='verify_by',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='office.employee'),
        ),
    ]
