# Generated by Django 5.0.7 on 2024-08-13 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0014_machine'),
        ('store', '0008_remove_in_item_employee_remove_out_item_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='out_item',
            name='verify_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='office.employee'),
        ),
    ]
