# Generated by Django 5.0.7 on 2024-08-13 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0015_delete_machine'),
        ('store', '0009_alter_out_item_verify_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher_name',
            name='verify_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='office.employee'),
        ),
    ]
