# Generated by Django 5.0.7 on 2024-08-13 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0019_operator_helper_limit'),
        ('store', '0010_alter_voucher_name_verify_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_item',
            name='machine',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='office.machine'),
        ),
        migrations.AddField(
            model_name='in_item',
            name='operator',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='office.operator'),
        ),
    ]
