# Generated by Django 5.0.7 on 2024-08-16 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0021_machine_working_status'),
        ('store', '0011_in_item_machine_in_item_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_status', models.IntegerField(default=0, null=True)),
                ('machine', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='office.machine')),
                ('operator', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='office.operator')),
            ],
        ),
    ]
