# Generated by Django 5.0.7 on 2024-08-16 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0021_machine_working_status'),
        ('store', '0012_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='Select_operator_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='office.item')),
                ('operator', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='office.operator')),
            ],
        ),
    ]
