# Generated by Django 5.0.7 on 2024-08-16 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_select_operator_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_item',
            name='shift',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.shift'),
        ),
    ]
