# Generated by Django 5.0.7 on 2024-08-16 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_in_item_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_item',
            name='shift',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.shift'),
        ),
    ]
