# Generated by Django 5.0.7 on 2024-08-16 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_in_item_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_item',
            name='shift',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.shift'),
        ),
    ]
