# Generated by Django 5.0.7 on 2024-08-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_in_item_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='in_item',
            name='shift',
        ),
    ]
