# Generated by Django 5.0.7 on 2024-08-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_in_item_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
