# Generated by Django 5.0.7 on 2024-08-22 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_shift_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='date',
        ),
    ]
