# Generated by Django 5.0.7 on 2024-08-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_remove_shift_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher_name',
            name='verify_status',
            field=models.IntegerField(null=True),
        ),
    ]
