# Generated by Django 5.0.7 on 2024-08-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_voucher_name_verify_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='generate_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
