# Generated by Django 5.0.7 on 2024-08-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr_code',
            name='sr_num',
            field=models.IntegerField(null=True),
        ),
    ]
