# Generated by Django 5.0.7 on 2024-08-02 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_qr_code_sr_num'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='product',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='qr_code',
            old_name='product',
            new_name='item',
        ),
    ]
