# Generated by Django 5.0.7 on 2024-08-11 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_alter_qr_code_batch_alter_qr_code_employee_and_more'),
        ('store', '0007_voucher_name_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Office_Employee',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='employee',
            new_name='office_employee',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='employee',
            new_name='office_employee',
        ),
        migrations.RenameField(
            model_name='qr_code',
            old_name='employee',
            new_name='office_employee',
        ),
    ]
