# Generated by Django 5.0.7 on 2024-08-11 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0009_rename_employee_office_employee_and_more'),
        ('store', '0007_voucher_name_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Office_Employee',
            new_name='Employee',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='office_employee',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='office_employee',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='qr_code',
            old_name='office_employee',
            new_name='employee',
        ),
    ]
