# Generated by Django 5.0.7 on 2024-08-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0010_rename_office_employee_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='In_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.IntegerField(max_length=100)),
                ('pin', models.IntegerField(max_length=50)),
                ('department', models.CharField(default=True, max_length=50)),
                ('status', models.IntegerField(default=1)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Out_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.IntegerField(max_length=100)),
                ('pin', models.IntegerField(max_length=50)),
                ('department', models.CharField(default=True, max_length=50)),
                ('status', models.IntegerField(default=1)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
