# Generated by Django 5.0.7 on 2024-08-11 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0011_in_employee_out_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='in_employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='out_employee',
            name='department',
        ),
    ]
