# Generated by Django 5.0.7 on 2024-08-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0012_remove_employee_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sr_num',
            field=models.IntegerField(null=True),
        ),
    ]
