# Generated by Django 5.0.7 on 2024-08-13 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0014_machine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Machine',
        ),
    ]
