# Generated by Django 5.0.7 on 2024-08-13 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0017_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_employee',
            name='operator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='office.operator'),
        ),
        migrations.AddField(
            model_name='in_employee',
            name='working_status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
