# Generated by Django 5.0.7 on 2024-08-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0018_in_employee_operator_in_employee_working_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='helper_limit',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
