# Generated by Django 5.0.7 on 2024-08-13 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0019_operator_helper_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='employee',
        ),
        migrations.AddField(
            model_name='batch',
            name='in_employee',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='office.in_employee'),
        ),
    ]
