# Generated by Django 5.0.7 on 2024-08-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0020_remove_batch_employee_batch_in_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='working_status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
