# Generated by Django 5.0.7 on 2024-08-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0023_alter_in_employee_mobile_alter_in_employee_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='helper_limit',
            field=models.IntegerField(null=True),
        ),
    ]
