# Generated by Django 5.0.7 on 2024-08-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0024_alter_operator_helper_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='operator',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
